# Generated by Django 2.1.2 on 2018-11-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='internshipmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='internshipmember',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='internshipmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='members',
        ),
        migrations.DeleteModel(
            name='InternshipMember',
        ),
        migrations.AddField(
            model_name='internshiplike',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeships', to='internships.Internship'),
        ),
        migrations.AddField(
            model_name='internshiplike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internship',
            name='likes',
            field=models.ManyToManyField(through='internships.InternshipLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='internshiplike',
            unique_together={('internship', 'user')},
        ),
    ]
