# Generated by Django 2.1.2 on 2018-11-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='skillmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skillmember',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skillmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='members',
        ),
        migrations.DeleteModel(
            name='SkillMember',
        ),
        migrations.AddField(
            model_name='skilllike',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeships', to='skills.Skill'),
        ),
        migrations.AddField(
            model_name='skilllike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='likes',
            field=models.ManyToManyField(through='skills.SkillLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skilllike',
            unique_together={('skill', 'user')},
        ),
    ]
