# Generated by Django 2.1.2 on 2018-11-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.DeleteModel(
            name='CourseMember',
        ),
        migrations.AddField(
            model_name='courselike',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeships', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='courselike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(through='courses.CourseLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courselike',
            unique_together={('course', 'user')},
        ),
    ]
